#pip install matplotlib pillow numpy


import streamlit as st
import matplotlib.pyplot as plt
from PIL import Image, ImageDraw, ImageFont
import pandas as pd
import io
import os
import numpy as np # Needed for array manipulation in PIL/Matplotlib

# --- CONFIGURATION (Based on your Graphic Design choices) ---
TEMPLATE_WIDTH = 1600
TEMPLATE_HEIGHT = 1000
CHART_WIDTH = 1200
CHART_HEIGHT = 600
HEADER_COLOR = "#3F51B5" # Your brand color
TITLE_COLOR = "#FFFFFF"

# --- CORE FUNCTION: CHART GENERATION (PYTHON DATA PROCESSING) ---

def create_chart_buffer(df, title_text):
    """Generates a chart from a DataFrame and returns it as a PIL Image."""
    
    # 1. Prepare Data for Matplotlib
    labels = df['Category'].tolist()
    values = df['Value'].tolist()
    
    # 2. Setup Figure and Axes
    # Use 'agg' backend for better performance in non-GUI environments (like Streamlit hosting)
    plt.switch_backend('Agg') 
    fig, ax = plt.subplots(figsize=(CHART_WIDTH / 100, CHART_HEIGHT / 100), dpi=100)
    
    # 3. Design-Focused Chart Plotting
    colors = ['#4CAF50' if v > df['Value'].mean() else '#FFC107' for v in values] # Conditional color based on mean
    ax.bar(labels, values, color=colors, zorder=3)
    
    # 4. Cleanup for Infographic Style
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_visible(False)
    ax.yaxis.set_visible(False)
    
    plt.xticks(fontsize=14)
    ax.set_title(title_text, fontsize=20, pad=20)
    
    # Add data labels
    for i, v in enumerate(values):
        ax.text(i, v + 200, f'${v:,.0f}', ha='center', color='black', fontsize=16)

    # 5. Save chart to in-memory buffer
    buf = io.BytesIO()
    plt.savefig(buf, transparent=True, bbox_inches='tight', pad_inches=0.1)
    plt.close(fig)
    buf.seek(0)
    
    # Convert buffer to PIL Image
    return Image.open(buf)

# --- CORE FUNCTION: IMAGE COMPOSITION (GRAPHIC DESIGN AUTOMATION) ---

def create_infographic_composition(chart_img, infographic_title):
    """Combines the chart image with the template and returns the final PIL Image."""
    
    # 1. Create the Template Canvas
    infographic = Image.new('RGB', (TEMPLATE_WIDTH, TEMPLATE_HEIGHT), color='#FFFFFF')
    draw = ImageDraw.Draw(infographic)
    
    # Draw the top banner (Your Graphic Design Element)
    draw.rectangle([0, 0, TEMPLATE_WIDTH, 150], fill=HEADER_COLOR) 
    
    # 2. Add Titles and Branding Text
    try:
        # Use a system font (Arial is common)
        font_title = ImageFont.truetype("arial.ttf", 60)
        font_text = ImageFont.truetype("arial.ttf", 30)
    except IOError:
        font_title = ImageFont.load_default()
        font_text = ImageFont.load_default()
            
    # Main Infographic Title from user input
    draw.text((80, 40), infographic_title, fill=TITLE_COLOR, font=font_title)
    
    # Branding/Source Footer
    draw.text((80, 920), "Generated by [Your Brand Name]. Data Analysis Automation Tool.", 
              fill="#9E9E9E", font=font_text)

    # 3. Paste the Generated Chart (Centering the chart)
    x_pos = (TEMPLATE_WIDTH - chart_img.width) // 2
    y_pos = 250
    
    # Convert chart image to have an alpha channel before pasting (if it doesn't already)
    if chart_img.mode != 'RGBA':
        chart_img = chart_img.convert('RGBA')
        
    infographic.paste(chart_img, (x_pos, y_pos), chart_img)
    
    return infographic

# --- STREAMLIT APPLICATION LAYOUT ---

st.set_page_config(
    page_title="SEO Infographic Generator",
    layout="centered",
    initial_sidebar_state="auto"
)

st.title("📈 The Automated Infographic Builder")
st.markdown("Upload your data and instantly generate a visually clean, SEO-ready infographic for your blog or report. **(The 'Tool Builder' in action!)**")
st.markdown("---")

# --- USER INPUTS ---

# 1. Infographic Title
infographic_title = st.text_input(
    "1. Enter the Main Infographic Title:",
    "Q3 2025 Revenue Deep Dive"
)

# 2. Data Upload
uploaded_file = st.file_uploader(
    "2. Upload your Data (.CSV format)",
    type=['csv'],
    help="Your CSV must have two columns: 'Category' and 'Value'."
)

# --- PROCESSING AND OUTPUT ---

if uploaded_file is not None:
    try:
        # Read the uploaded CSV file into a Pandas DataFrame
        data_df = pd.read_csv(uploaded_file)
        
        # Validate required columns
        if 'Category' not in data_df.columns or 'Value' not in data_df.columns:
            st.error("❌ Error: CSV must contain 'Category' and 'Value' columns.")
        else:
            # 1. Generate the Chart Image
            chart_img = create_chart_buffer(data_df, infographic_title)
            
            # 2. Combine Chart with Template/Design
            final_infographic = create_infographic_composition(chart_img, infographic_title)
            
            st.markdown("---")
            st.subheader("🎉 Your Automated Infographic:")
            
            # 3. Display the final image
            st.image(final_infographic, caption=infographic_title, use_column_width=True)
            
            # 4. Add a Download Button
            
            # Convert final PIL Image to bytes for download
            img_bytes = io.BytesIO()
            final_infographic.save(img_bytes, format='PNG')
            
            st.download_button(
                label="⬇️ Download Infographic (PNG)",
                data=img_bytes.getvalue(),
                file_name="automated_infographic.png",
                mime="image/png"
            )

    except Exception as e:
        st.error(f"An error occurred during processing: {e}")
        st.info("Please ensure your CSV data is clean (e.g., 'Value' column contains only numbers).")

# Optional: Display example data for user guidance
st.sidebar.markdown("---")
st.sidebar.subheader("Data Format Example:")
example_data = {
    'Category': ['SEO', 'Email', 'Paid Ads'],
    'Value': [12500, 15000, 8900]
}
st.sidebar.dataframe(pd.DataFrame(example_data), hide_index=True)
